
[project]
name = "embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "httpx==0.28.1",
]

[dependency-groups]
dev = [
    "pytest==8.3.4",
    "pytest-asyncio==0.25.2",
]